swagger: "2.0"
info:
  title: University API
  description: Swagger based project
  version: 1.0.0
host: localhost:8080
schemes:
  - http
basePath: "/api"
paths:
  /students/save:
    post:
      tags:
        - "students"
      summary: "Create new student"
      description: "Requires unique firstName and lastName"
      operationId: "save"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Created new student"
          required: true
          schema:
            $ref: "#/definitions/StudentDTO"
      responses:
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
definitions:
  StudentDTO:
    type: "object"
    required: [ id, firstName, lastName, course ]
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
        pattern: "[A-Z][a-z]{3,30}"
      lastName:
        type: "string"
        pattern: "[A-Z][a-z]{3,30}"
      course:
        type: "integer"
        format: "int32"
        description: "Course (1-5)"
        minimum: 1
        maximum: 5
      group:
        type: object
        $ref: "#/definitions/GroupDTO"
  GroupDTO:
    type: object
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: string
        pattern: "[A-Z][a-z]{3,30}"