DROP TABLE IF EXISTS public.students CASCADE;

DROP TABLE IF EXISTS public.groups CASCADE;

DROP TABLE IF EXISTS public.teacher CASCADE;

DROP TABLE IF EXISTS public.students_teacher CASCADE;

DROP TABLE IF EXISTS public.classroom CASCADE ;

DROP TABLE IF EXISTS public.events CASCADE ;

DROP TABLE IF EXISTS public.subject CASCADE ;

