DROP TABLE IF EXISTS classrooms CASCADE;

DROP TABLE IF EXISTS groups CASCADE;

DROP TABLE IF EXISTS events CASCADE;

DROP TABLE IF EXISTS students CASCADE;

DROP TABLE IF EXISTS subjects CASCADE;

DROP TABLE IF EXISTS teachers CASCADE;

DROP TABLE IF EXISTS teacher_subjects CASCADE ;


