DROP TABLE IF EXISTS classrooms CASCADE;

DROP TABLE IF EXISTS day_schedules CASCADE;

DROP TABLE IF EXISTS day_schedules_lessons CASCADE;

DROP TABLE IF EXISTS groups CASCADE;

DROP TABLE IF EXISTS lessons CASCADE;

DROP TABLE IF EXISTS lessons_time CASCADE;

DROP TABLE IF EXISTS month_schedules CASCADE;

DROP TABLE IF EXISTS month_schedules_week_schedules CASCADE;

DROP TABLE IF EXISTS schedules CASCADE;

DROP TABLE IF EXISTS schedules_month_schedules CASCADE;

DROP TABLE IF EXISTS students CASCADE;

DROP TABLE IF EXISTS subjects CASCADE;

DROP TABLE IF EXISTS teachers CASCADE;

DROP TABLE IF EXISTS teacher_subjects CASCADE ;

DROP TABLE IF EXISTS week_schedules CASCADE ;

DROP TABLE IF EXISTS week_schedules_day_schedules CASCADE ;

